#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: meson
# autospec version: v20
# autospec commit: 7a85b05ed284
#
Name     : netplan
Version  : 1.1.1
Release  : 13
URL      : https://github.com/canonical/netplan/archive/1.1.1/netplan-1.1.1.tar.gz
Source0  : https://github.com/canonical/netplan/archive/1.1.1/netplan-1.1.1.tar.gz
Summary  : Network configuration tool using YAML
Group    : Development/Tools
License  : GPL-3.0 GPL-3.0-only
Requires: netplan-bin = %{version}-%{release}
Requires: netplan-data = %{version}-%{release}
Requires: netplan-lib = %{version}-%{release}
Requires: netplan-libexec = %{version}-%{release}
Requires: netplan-license = %{version}-%{release}
Requires: netplan-man = %{version}-%{release}
Requires: netplan-python = %{version}-%{release}
Requires: netplan-python3 = %{version}-%{release}
Requires: PyYAML
Requires: pypi-netifaces
Requires: pypi-rich
BuildRequires : bash-completion-dev
BuildRequires : buildreq-meson
BuildRequires : glib-dev
BuildRequires : pandoc
BuildRequires : pkgconfig(bash-completion)
BuildRequires : pkgconfig(cmocka)
BuildRequires : pkgconfig(glib-2.0)
BuildRequires : pkgconfig(libsystemd)
BuildRequires : pkgconfig(systemd)
BuildRequires : pkgconfig(yaml-0.1)
BuildRequires : pypi(cffi)
BuildRequires : pypi(pytest)
BuildRequires : pypi(yaml)
BuildRequires : pypi-coverage
BuildRequires : pypi-pycodestyle
BuildRequires : pypi-pyflakes
BuildRequires : pypi-pytest
BuildRequires : python3-dev
BuildRequires : yaml-dev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}
Patch1: 0001-Fix-meson-deps.patch

%description
netplan reads network configuration from /etc/netplan/*.yaml which are written by administrators,
installers, cloud image instantiations, or other OS deployments. During early boot, it generates
backend specific configuration files in /run to hand off control of devices to a particular
networking daemon.

Currently supported backends are NetworkManager and systemd-networkd.

%package bin
Summary: bin components for the netplan package.
Group: Binaries
Requires: netplan-data = %{version}-%{release}
Requires: netplan-libexec = %{version}-%{release}
Requires: netplan-license = %{version}-%{release}

%description bin
bin components for the netplan package.


%package data
Summary: data components for the netplan package.
Group: Data

%description data
data components for the netplan package.


%package dev
Summary: dev components for the netplan package.
Group: Development
Requires: netplan-lib = %{version}-%{release}
Requires: netplan-bin = %{version}-%{release}
Requires: netplan-data = %{version}-%{release}
Provides: netplan-devel = %{version}-%{release}
Requires: netplan = %{version}-%{release}

%description dev
dev components for the netplan package.


%package doc
Summary: doc components for the netplan package.
Group: Documentation
Requires: netplan-man = %{version}-%{release}

%description doc
doc components for the netplan package.


%package lib
Summary: lib components for the netplan package.
Group: Libraries
Requires: netplan-data = %{version}-%{release}
Requires: netplan-libexec = %{version}-%{release}
Requires: netplan-license = %{version}-%{release}

%description lib
lib components for the netplan package.


%package libexec
Summary: libexec components for the netplan package.
Group: Default
Requires: netplan-license = %{version}-%{release}

%description libexec
libexec components for the netplan package.


%package license
Summary: license components for the netplan package.
Group: Default

%description license
license components for the netplan package.


%package man
Summary: man components for the netplan package.
Group: Default

%description man
man components for the netplan package.


%package python
Summary: python components for the netplan package.
Group: Default
Requires: netplan-python3 = %{version}-%{release}

%description python
python components for the netplan package.


%package python3
Summary: python3 components for the netplan package.
Group: Default
Requires: python3-core

%description python3
python3 components for the netplan package.


%prep
%setup -q -n netplan-1.1.1
cd %{_builddir}/netplan-1.1.1
%patch -P 1 -p1
pushd ..
cp -a netplan-1.1.1 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1729096600
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
meson --libdir=lib64 --prefix=/usr --buildtype=plain   builddir
ninja -v -C builddir
GOAMD64=v3
CFLAGS="$CFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 " CXXFLAGS="$CXXFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 " LDFLAGS="$LDFLAGS -march=x86-64-v3 " meson --libdir=lib64 --prefix=/usr --buildtype=plain   builddiravx2
ninja -v -C builddiravx2

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
meson test -C builddir --print-errorlogs || :
cd ../buildavx2;
meson test -C builddir --print-errorlogs || : || :

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
mkdir -p %{buildroot}/usr/share/package-licenses/netplan
cp %{_builddir}/netplan-%{version}/COPYING %{buildroot}/usr/share/package-licenses/netplan/8624bcdae55baeef00cd11d5dfcfa60f68710a02 || :
GOAMD64=v3
DESTDIR=%{buildroot}-v3 ninja -C builddiravx2 install
GOAMD64=v2
DESTDIR=%{buildroot} ninja -C builddir install
## install_append content
# Remove the symlink /lib/netplan/generate, which according to upstream should go away soon
rm -rf %{buildroot}/lib

# Make sure we don't create and install a /usr/sbin directory from this package -- it's a symlink in the base filesystem
mkdir -p %{buildroot}/usr/bin
mv %{buildroot}/usr/sbin/* %{buildroot}/usr/bin/
rmdir %{buildroot}/usr/sbin
## install_append end
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)
/usr/lib/systemd/system-generators/netplan

%files bin
%defattr(-,root,root,-)
/usr/bin/netplan

%files data
%defattr(-,root,root,-)
/usr/share/bash-completion/completions/netplan
/usr/share/dbus-1/system-services/io.netplan.Netplan.service
/usr/share/dbus-1/system.d/io.netplan.Netplan.conf
/usr/share/netplan/netplan.script
/usr/share/netplan/netplan_cli/__init__.py
/usr/share/netplan/netplan_cli/_features.py
/usr/share/netplan/netplan_cli/cli/__init__.py
/usr/share/netplan/netplan_cli/cli/commands/__init__.py
/usr/share/netplan/netplan_cli/cli/commands/apply.py
/usr/share/netplan/netplan_cli/cli/commands/generate.py
/usr/share/netplan/netplan_cli/cli/commands/get.py
/usr/share/netplan/netplan_cli/cli/commands/info.py
/usr/share/netplan/netplan_cli/cli/commands/ip.py
/usr/share/netplan/netplan_cli/cli/commands/migrate.py
/usr/share/netplan/netplan_cli/cli/commands/set.py
/usr/share/netplan/netplan_cli/cli/commands/sriov_rebind.py
/usr/share/netplan/netplan_cli/cli/commands/status.py
/usr/share/netplan/netplan_cli/cli/commands/try_command.py
/usr/share/netplan/netplan_cli/cli/core.py
/usr/share/netplan/netplan_cli/cli/ovs.py
/usr/share/netplan/netplan_cli/cli/sriov.py
/usr/share/netplan/netplan_cli/cli/state.py
/usr/share/netplan/netplan_cli/cli/state_diff.py
/usr/share/netplan/netplan_cli/cli/utils.py
/usr/share/netplan/netplan_cli/configmanager.py
/usr/share/netplan/netplan_cli/terminal.py

%files dev
%defattr(-,root,root,-)
/usr/include/netplan/netdef.h
/usr/include/netplan/netplan.h
/usr/include/netplan/parse-nm.h
/usr/include/netplan/parse.h
/usr/include/netplan/state.h
/usr/include/netplan/types.h
/usr/include/netplan/util.h
/usr/lib64/libnetplan.so
/usr/lib64/pkgconfig/netplan.pc

%files doc
%defattr(0644,root,root,0755)
/usr/share/doc/netplan/*

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/libnetplan.so.1
/usr/lib64/libnetplan.so.1

%files libexec
%defattr(-,root,root,-)
/V3/usr/libexec/netplan/generate
/V3/usr/libexec/netplan/netplan-dbus
/usr/libexec/netplan/generate
/usr/libexec/netplan/netplan-dbus

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/netplan/8624bcdae55baeef00cd11d5dfcfa60f68710a02

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man5/netplan.5
/usr/share/man/man8/netplan-apply.8
/usr/share/man/man8/netplan-dbus.8
/usr/share/man/man8/netplan-generate.8
/usr/share/man/man8/netplan-get.8
/usr/share/man/man8/netplan-info.8
/usr/share/man/man8/netplan-ip.8
/usr/share/man/man8/netplan-rebind.8
/usr/share/man/man8/netplan-set.8
/usr/share/man/man8/netplan-status.8
/usr/share/man/man8/netplan-try.8

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/V3/usr/lib/python3*/*
/usr/lib/python3*/*
